### ISSUE TITLE
Parsing "Math.random()" get same values

### ISSUE THREAD

**Issue by Watunder** [uyjulian/pytjs#2]
Thanks for your work , I made a tjs2 parser plugin for godot with `pytjs/src/krkr_minimal` ...
**the bug is when a timer call `ScriptEngine->EvalExpression` parse `"Math.random()"`  _frequently_ (timeout < 0.5s）get this output ↓**

    0.542758
    0.519828
    0.845591
    0.845591 // same value
    0.845591 // same value
    0.743373
    0.743373

### method called by godot

    func _on_TJS2Parser_Timer_timeout()):

	    tjs2parser = load(plugin_tjs2parser).new()
	    
	    var result = tjs2parser.method("Math.random()")
		    
	    print(result)

### the method in dll

    godot::Variant
    tTJSWrapper::EvalExpression(godot::Variant script, godot::Object context, godot::Variant name,godot::Variant lineofs) {
    
        tTJSVariant result;
        iTJSDispatch2* context_dispatch = NULL;
    
        ttstr tjs_script = Variant_GDtoTJS(script);
        ttstr tjs_name = Variant_GDtoTJS(name);
        tjs_int tjs_lineofs = Variant_GDtoTJS(lineofs);
    
        ScriptEngine->EvalExpression(tjs_script,
                                     &result,
                                     context_dispatch,
                                     tjs_name.GetLen() > 0 ? &tjs_name : NULL,
                                     tjs_lineofs);
    
        return Variant_TJStoGD(result);
    }

### register method

    godot::Variant
    TJS2Parser::method(godot::Variant arg) {
      
      tTJSWrapper wrapper_tjs;
      godot::Variant result = wrapper_tjs.EvalExpression(Variant(arg), Object(), Variant(), Variant());

      return result;
    }

**Comment by uyjulian** [comment]
`Math.random`  cannot guarantee unique values, so if you need unique values, I would recommend using a different random implementation.

It seems you are instantiating a new script engine every frame. This will reset the seed to the current time every time you do this, so I recommend keeping a script engine around and running the expression multiple times on one script engine.

**Comment by Watunder** [comment]
Changes have been made as you suggested,  it works well～ thanks ✧(≖ ◡ ≖✿)
